server:
  port: 8086
  servlet:
    context-path: /estoque
spring:
  application:
    name: estoque
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tempdb
    username: postgres
    password: postgres
  #rabbitmq:
    #host: localhost
    #port: 5672
    #username: admin
    #password: admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registro/eureka

estoque:
  seguranca:
    jwtTokenConfig:
      segredo: ${JWT_SECRET:crudapps}
      expiracao: 432000
  api-info:
    titulo: Estoque API
    descricao: Documentação da API para acesso aos endpoints do Estoque
    versao: 1.0
    pacote: br.com.conductor.estoque.rest.controller
