version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: crudbd
    volumes:
      - ./pgdata:/var/lib/postgresql/datadb1
    ports:
      - "5432:5432"
  db2:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pagamento
    volumes:
      - ./pgdata:/var/lib/postgresql/datadb2
    ports:
      - "5433:5432"
  db3:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
    volumes:
      - ./pgdata:/var/lib/postgresql/datadb3
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - CLUSTERED=true
    volumes:
      - $PWD/storage/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
